skillKeywords = [{"ActiveMQ": []}, {"ADO.NET": ["ADO .NET", "ADONET"]}, {"Airflow": []}, {"AJAX": []}, {"Akka": []}, {"AMQP": []}, {"Android": []}, {"Angular" : ["AngularJS", "Angular.JS"]}, {"Ansible": []}, {"Ant": []}, {"Apache": []}, {"ApacheMQ": []}, {"Apex": []}, {"Artifactory": []}, {"ASP": ["Active Server Pages"]}, {"ASP.NET": ["ASP .NET", "ASPNET"]}, {"AWS": ["Amazon Web Services"]}, {"Backbone": ["BackboneJS"]}, {"Balsamiq": []}, {"Bluetooth": []}, {"Bootstrap": ["BootstrapJS", "Bootstrap.JS"]}, {"Bottle": []},
		 {"C++": []}, {"C#": []}, {"CakePHP": []}, {"Capistrano": []}, {"Cassandra": []}, {"Ceph": []}, {"Celery": []}, {"Chai": []}, {"Chef": []},  {"ClearCase": ["Clear Case"]}, {"Clojure": []}, {"ClojureScript": ["Clojure Script"]}, {"CloudFoundry": []}, {"COBOL": []}, {"Cocoa": []},  {"CodeIgniter": []}, {"CoffeeScript": ["Coffee Script"]}, {"Cognos": []}, {"ColdFusion": ["Cold Fusion"]}, {"Cordova": []}, {"Corticon": []}, {"Couch": ["CouchDB"]}, {"CSLA": []}, {"CSS": []}, {"CSS3": []}, {"Crystal Reports": []}, {"Cucumber": []},
		 {"Dart": []}, {"D3": ["D3JS", "D3.JS"]}, {"Delphi": []}, {"DevExpress": ["Dev Express"]}, {"DevOps": []}, {"DirectX": []}, {"Django": []}, {"Docker": []}, {"Drools": []}, {"Dropwizard": []}, {"Dynamo": ["DynamoDB"]},
		 {"Eclipse": []}, {"Entity Framework": ["EF", "EF4", "EF5", "EF6"]}, {"Ehcache": []}, {"Elastic": ["Elasticsearch"]}, {"ElastiCache": []}, {"Elixir": []}, {"Elm": []}, {"Ember": ["EmberJS", "Ember.JS"]}, {"Erlang": []}, {"ES6": []}, {"ESRI": []}, {"ETL": []}, {"ExpressionEngine": []}, {"ExpressJS": ["Express.JS"]}, {"ExtJS": ["Ext.JS"]},
		 {"Flash": []}, {"Flask": []},  {"Flume": []}, {"Fortran": []}, {"FoxPro": []}, {"GIS": []}, {"Git": []},
		 {"Glassfish": []}, {"Golang": []}, {"Gradle": []}, {"Grunt": []}, {"Guava": []}, {"Gulp": []}, 
		 {"Hadoop": []}, {"Handlebar": ["HandlebarJS", "Handlebars", "HandlebarsJS"]}, {"Hapi": ["HapiJS"]}, {"Haskell": []}, {"HBase": []}, {"Hibernate": []}, {"Hive": []}, {"HTML": []}, {"HTML5": []}, {"Hudson": []}, 
		 {"IIS": ["Internet Information Services"]}, {"iLog": []}, {"Impala": []}, {"Informatica": []}, {"IntelliJ": []}, {"Ionic": []}, {"iOS": []},
		 {"J2EE": []}, {"Jasmine": []}, {"Java": []}, {"JSF": ["Java Server Faces"]}, {"JSP": ["Java Server Pages"]}, {"Javascript": ["Java Script"]}, {"JAXRS": []}, {"JAXWS": []}, {"JBOSS": []}, {"JCE": []}, {"JDBC": []}, {"Jenkins": []}, {"JMeter": []}, {"JMS": []}, {"JNDI": []}, {"JPA": ["Java Persistence API"]}, {"JQuery": []}, {"JSON": []}, {"JUnit": []}, {"Kafka": []}, {"Kendo": ["KendoJS"]}, {"Kettle": []}, {"Kinesis": []}, {"Knockout": ["KnockoutJS", "Knockout.JS"]}, {"Koa": ["KoaJS", "Koa.JS"]}, {"Kohana": []}, {"Kubernetes": []}, {"Labview": []}, {"LAMP": []}, {"Laravel": []}, {"Liquibase": []}, {"Lua": []}, {"Lucene": []}, {"Linux": []}, {"Magento": []}, {"Marionette": ["MarionetteJS", "Marionette.JS"]}, {"Matlab": []}, {"Maven": []}, {"Memcached": []}, {"Mercurial": ["Hg"]}, {"Mesos": []}, {"Meteor": ["MeteorJs", "Meteor.Js"]},  {"Mocha": []},  {"Mockito": []}, {"Mongo": ["MongoDB"]}, {"Mono": []}, {"MQTT": []}, {"MSBI": []}, {"MSMQ": ["MS MQ", "Microsoft Message Queue"]},  {"Mulesoft": ["Mule"]}, {"Mustache": [ "MustacheJS", "Mustache.JS"]}, {"MVC": ["MVC3", "MVC4", "MVC5"]}, {"MyBatis": []}, {"MySQL": ["My SQL"]}, {"Neo4j": []},
		 {".NET": []}, {"NHibernate": []}, {"Node": ["NodeJS", "Node.JS"]}, {"Nose": []}, {"NoSQL": []}, {"npm": []}, {"NUnit": []}, {"Objective C": ["Objective-C", "ObjectiveC"]}, {"Octopus": []}, {"Open GL": ["OpenGL"]}, {"Openstack": []}, {"Oracle": []}, {"OWIN": []}, {"Pentaho": []}, {"PeopleSoft": []}, {"Perl": []}, {"Phonegap": []}, {"Photoshop": []}, {"PHP": []}, {"PHPUnit": []}, {"PL/SQL": []}, {"Polymer": []}, {"PostGIS": []}, {"Postgres": ["PostgresQL", "Postgre SQL"]}, {"Pyside": []}, {"Python": []}, {"Puppet": []}, {"RabbitMQ": ["Rabbit MQ"]}, {"Raven": ["RavenDB"]}, {"RDBMS": ["relational database", "relational databases"]}, {"React": ["ReactJS", "React.JS"]}, {"ReactNative": ["React Native"]}, {"Redis": []}, {"REST": ["RESTful"]}, {"Rhino": ["RhinoMocks"]}, {"Ruby": []}, {"Ruby on Rails": ["RoR"]}, {"Rust": []}, {"S3": []}, {"Sails": ["SailsJs", "Sails.Js"]}, {"Salesforce": ["Sales Force"]}, {"Saltstack": []}, {"SAP": []}, {"Sass": []}, {"Scala": []}, {"SCSS": []}, {"Selenium": []}, {"Siebel": []}, {"SignalR": []}, {"Silverlight": ["Silver Light"]}, {"SOA": ["Service Oriented Architecture", "Service-Oriented Architecture"]}, {"SOAP": []}, {"SOLR": []},{"Sonar": []}, {"Sparx": []}, {"Sphinx": []}, {"Spotfire": []}, {"Spring": []}, {"SQL": ["Structured Query Language"]}, {"SQL Server": ["SQLServer", "MSSQL", "MS SQL"]}, {"SQLAlchemy": ["SQL Alchemy"]}, {"SSIS": ["SQL Server Integration Services"]}, {"SSRS": ["SQL Server Reporting Services"]}, {"Struts": []}, {"Subversion": ["SVN"]}, {"Swarm": []}, {"Swift": []}, {"Sybase": []}, {"Symfony": []},
		 {"TFS": ["Team Foundation Server"]}, {"TestNG": []}, {"Telerik": []}, {"Teradata": []}, {"Tomcat": []}, {"Toplink": []}, {"TransactSQL": ["Transact SQL", "Transact-SQL", "TSQL", "T-SQL"]}, {"Typescript": []}, {"UIKit": ["UI Kit"]}, {"Underscore": ["UnderscoreJS"]}, {"UML": ["Universal Modeling Language"]}, {"Unity": ["Unity3D"]}, {"UNIX": []}, {"Unreal": []},  {"Vagrant": []}, {"VB.NET": ["VB .NET", "VBNET"]}, {"Visio": []}, {"Visual Basic": ["VB"]}, {"Visual Studio": ["VS", "VS2005", "VS2008", "VS2010", "VS2012", "VS2013", "VS2015"]}, {"Vue": ["VueJs", "Vue.Js"]}, {"VMWare": ["VM Ware"]},
		 {"Watin": []}, {"Watir": []}, {"WCF": ["Windows Communication Foundation"]}, {"WebAPI": ["Web API"]}, {"Web Services": ["WebServices"]}, {"Webdriver": ["Web Driver"]},  {"WebLogic": ["Web Logic"]}, {"WebRTC": ["Web RTC"]}, {"WebSockets": ["Web Sockets"]}, {"Websphere": ["Web Sphere"]}, {"Winforms": ["Winform", "Win Form", "Win Forms"]}, {"WPF": ["Windows Presentation Foundation"]}, {"Xamarin": []}, {"XCode": []}, {"XML": []}, {"xUnit": []}, {"Zend": []}, {"ZeroMQ": ["Zero MQ"]}]



synonymsDictionary = {'angularjs': 'angular', 'backbonejs': 'backbone', 'bootstrapjs': 'bootstrap', 'couchdb': 'couch',
		      'd3js': 'd3', 'dynamodb': 'dynamo', 'ef': 'entity framework', 'ef4': 'entity framework', 'ef5': 'entity framework', 'ef6': 'entity framework', 'elasticsearch': 'elastic', 'emberjs': 'ember', 'handlebar': 'handlebars', 'handlebarjs': 'handlebars', 'handlebarsjs': 'handlebars', 'hapijs': 'hapi', 'internet information services': 'iis', 'Java Server Faces': 'JSF', 'knockoutjs': 'knockout', 'koajs': 'koa',
		      'marionettejs': 'marionette', 'mongodb': 'mongo', 'ms mq': 'msmq', 'mssql': 'sql server', 'ms sql': 'sql server', 'my sql': 'mysql',
		      'nodejs': 'node', 'objective c': 'objective-c', 'open gl': 'opengl', 'postgresql': 'postgres',
		      'ravendb': 'raven', 'reactjs': 'react.js', 'restful': 'rest', 'svn': 'subversion', 'sails.js': 'sails', 'sailsjs': 'sails', 'sqlserver': 'sql server',
                      'tfs': 'team foundation server',
                      'transactsql': 't-sql', 'transact sql': 't-sql', 'transact-sql': 't-sql', 'tsql': 't-sql',
		      'underscorejs': 'underscore', 'web api': 'webapi', 'webservices': 'web services', 'winform': 'winforms' }
