skillKeywords = [{"ActiveMQ": []}, {"ADO.NET": ["ADO .NET", "ADONET"]}, {"Airflow": []}, {"AJAX": []}, {"Akka": []}, {"AMQP": []}, {"Android": ["Andriod"]}, {"Angular" : ["AngularJS", "Angular.JS"]}, {"Ansible": []}, {"Ant": []}, {"Apache": []}, {"ApacheMQ": []}, {"Apache Spark": []}, {"Apex": []}, {"Artifactory": []}, {"ASP": ["Active Server Pages"]}, {"ASP.NET": ["ASP .NET", "ASPNET"]}, {"AWS": ["Amazon Web Services"]}, {"Backbone": ["BackboneJS"]}, {"Balsamiq": []}, {"Bitcoin": ["BTC"]}, {"Bluemix": ["Blue Mix"]}, {"Bluetooth": []}, {"Bootstrap": ["BootstrapJS", "Bootstrap.JS"]}, {"Bottle": []},
		 {"C++": []}, {"C#": []}, {"Caliburn": ["Caliburn.Micro"]}, {"CakePHP": []}, {"Capistrano": []}, {"Cassandra": []}, {"Ceph": []}, {"Celery": []}, {"Chai": []}, {"Chef": []}, {"CI/CD": ["CICD", "Continuous Delivery"]}, {"ClearCase": ["Clear Case"]}, {"Clojure": []}, {"ClojureScript": ["Clojure Script"]}, {"CloudFoundry": []}, {"COBOL": []}, {"Cocoa": []}, {"Cocoa Touch": []}, {"CodeIgniter": ["CodeIgnitor"]}, {"CoffeeScript": ["Coffee Script"]}, {"Cognos": []}, {"Compass": []}, {"ColdFusion": ["Cold Fusion"]}, {"Cordova": []}, {"Corticon": []}, {"Couch": ["CouchDB"]}, {"Couchbase": []}, {"CQRS": []}, {"CSLA": []}, {"CSS": []}, {"CSS3": []}, {"Crystal Reports": []}, {"Cucumber": []},
		 {"Dart": []}, {"D3": ["D3JS", "D3.JS"]}, {"Delphi": []}, {"DevExpress": ["Dev Express"]}, {"DevOps": []}, {"DirectX": []}, {"Django": []}, {"Django Rest Framework": ["DRF"]}, {"Docker": []}, {"Drools": []}, {"Dropwizard": []}, {"Dynamo": ["DynamoDB"]},
		 {"Eclipse": []}, {"Entity Framework": ["EF", "EF4", "EF5", "EF6"]}, {"Ehcache": []}, {"Elastic": ["Elasticsearch"]}, {"ElastiCache": []}, {"Elixir": []}, {"ELK": []}, {"Elm": []}, {"Ember": ["EmberJS", "Ember.JS"]}, {"Erlang": []}, {"ES6": []}, {"ESRI": []}, {"Ethereum": ["ETH"]}, {"ETL": []}, {"ExpressionEngine": []}, {"ExpressJS": ["Express.JS"]}, {"ExtJS": ["Ext.JS"]},
		 {"Flash": []}, {"Flask": []},  {"Flume": []}, {"Fortran": []}, {"FoxPro": []}, {"Gerrit": []}, {"GIS": []}, {"Git": []},
		 {"Glassfish": []}, {"Golang": []}, {"Gradle": []}, {"Grails": []}, {"GraphQL": ["Graph QL"]}, {"Groovy on Grails": []}, {"Grunt": []}, {"Guava": []}, {"Gulp": []}, 
		 {"Hadoop": []}, {"Handlebar": ["HandlebarJS", "Handlebars", "HandlebarsJS"]}, {"Hapi": ["HapiJS"]}, {"Haskell": []}, {"HBase": []}, {"Hibernate": []},  {"Highcharts": ["Highchart"]}, {"Hive": []},  {"HP ALM": ["HPALM", "HP Application Lifecycle Management"]}, {"HTML": []}, {"HTML5": []}, {"Hudson": []}, 
		 {"IIS": ["Internet Information Services"]}, {"iLog": []}, {"Impala": []}, {"Informatica": []}, {"IntelliJ": []}, {"Ionic": []}, {"iOS": []},
		 {"J2EE": []}, {"Jasmine": []}, {"Java": []}, {"JSF": ["Java Server Faces"]}, {"JSP": ["Java Server Pages"]}, {"Javascript": ["Java Script"]}, {"JAXRS": []}, {"JAXWS": ["JAX-WS"]}, {"JBOSS": []}, {"JCE": []}, {"JDBC": []}, {"Jenkins": []}, {"JHipster":[]}, {"Jinja": ["Jinja2"]}, {"JMeter": []}, {"JMS": []}, {"JNDI": []}, {"JPA": ["Java Persistence API"]}, {"JQuery": []}, {"JSON": []},  {"JSTL": []}, {"JUnit": []}, {"Kafka": []}, {"Kendo": ["KendoJS"]}, {"Kettle": []}, {"Kinesis": []}, {"Knockout": ["KnockoutJS", "Knockout.JS"]}, {"Koa": ["KoaJS", "Koa.JS"]}, {"Kohana": []}, {"Kubernetes": []}, {"Labview": []}, {"LAMP": []}, {"Laravel": []}, {"Liquibase": []}, {"Lua": []}, {"Lucene": []}, {"Linux": []}, {"Magento": []}, {"Marionette": ["MarionetteJS", "Marionette.JS"]}, {"Matlab": []}, {"Maven": []}, {"MEF": []}, {"Memcached": []}, {"Mercurial": ["Hg"]}, {"Mesos": []}, {"Meteor": ["MeteorJs", "Meteor.Js"]}, {"ML": ["Machine Learning"]}, {"Mocha": []},  {"Mockito": []}, {"Mongo": ["MongoDB", "MongoD"]}, {"Mono": []}, {"MQTT": []}, {"MSBI": []}, {"MSMQ": ["MS MQ", "Microsoft Message Queue"]},  {"Mulesoft": ["Mule"]}, {"Mustache": [ "MustacheJS", "Mustache.JS"]}, {"MVC": ["MVC3", "MVC4", "MVC5"]}, {"MyBatis": []}, {"MySQL": ["My SQL"]}, {"Neo4j": []},
		 {".NET": []}, {"NHibernate": []}, {"NLP": ["Natural Language Processing"]}, {"Node": ["NodeJS", "Node.JS"]}, {"Nose": []}, {"NoSQL": []}, {"npm": []}, {"NUnit": []}, {"OAuth": []}, {"Objective C": ["Objective-C", "ObjectiveC"]}, {"Octopus": []}, {"Open GL": ["OpenGL"]}, {"Openstack": []}, {"Oracle": []}, {"OWIN": []}, {"Pentaho": []}, {"PeopleSoft": []}, {"Perl": []}, {"Phonegap": []}, {"Photoshop": []}, {"PHP": []}, {"PHPUnit": []}, {"PL/SQL": []}, {"Polymer": []}, {"Protractor": []},  {"PostGIS": []}, {"Postgres": ["PostgresQL", "Postgre SQL"]}, {"Prism": []},  {"Pyramid": []}, {"Pyside": []}, {"Python": []}, {"Puppet": []}, {"RabbitMQ": ["Rabbit MQ"]}, {"Raven": ["RavenDB"]}, {"RDBMS": ["relational database", "relational databases"]}, {"React": ["ReactJS", "React.JS"]}, {"ReactNative": ["React Native"]}, {"Redis": []},  {"Redux": []}, {"REST": ["RESTful"]}, {"RESTeasy": []}, {"Rhino": ["RhinoMocks"]}, {"Ruby": []}, {"Ruby on Rails": ["RoR", "Rails"]}, {"Rust": []}, {"S3": []}, {"Sails": ["SailsJs", "Sails.Js"]}, {"Salesforce": ["Sales Force"]}, {"Saltstack": []}, {"SAP": []}, {"Sass": []}, {"Scala": []}, {"SCSS": []}, {"Selenium": ["Webdriver"]}, {"Sencha": []}, {"Siebel": []}, {"SignalR": []}, {"Silverlight": ["Silver Light"]}, {"SOA": ["Service Oriented Architecture", "Service-Oriented Architecture"]}, {"SOAP": []}, {"SOLR": []},{"Sonar": []}, {"Sparx": []}, {"Sphinx": []}, {"Spotfire": []}, {"Spring": []}, {"Spring Boot": ["SpringBoot"]}, {"Spring Cloud": ["SCF"]}, {"SQL": ["Structured Query Language"]}, {"SQL Server": ["SQLServer", "MSSQL", "MS SQL"]}, {"SQLAlchemy": ["SQL Alchemy"]}, {"SSIS": ["SQL Server Integration Services"]}, {"SSRS": ["SQL Server Reporting Services"]}, {"Struts": []}, {"Subversion": ["SVN"]}, {"Swarm": []}, {"Swift": []}, {"Sybase": []}, {"Symfony": []},
		 {"TFS": ["Team Foundation Server"]}, {"TestNG": []}, {"Telerik": []}, {"Teradata": []}, {"Terraform": []}, {"TIBCO": []}, {"Tomcat": []}, {"Toplink": []}, {"Tornado": []}, {"TransactSQL": ["Transact SQL", "Transact-SQL", "TSQL", "T-SQL"]}, {"Typescript": ["Type script"]}, {"UIKit": ["UI Kit"]}, {"Underscore": ["UnderscoreJS"]}, {"UML": ["Universal Modeling Language"]}, {"Unity": ["Unity3D"]}, {"UNIX": []}, {"Unreal": []}, {"UWP": ["Universal Windows Platform"]}, {"Vagrant": []}, {"VB.NET": ["VB .NET", "VBNET"]}, {"Visio": []}, {"Visual Basic": ["VB"]}, {"Visual Studio": ["VS", "VS2005", "VS2008", "VS2010", "VS2012", "VS2013", "VS2015"]}, {"Vue": ["VueJs", "Vue.Js"]}, {"VMWare": ["VM Ware", "VM-Ware"]},
		 {"Watin": []}, {"Watir": []}, {"WCF": ["Windows Communication Foundation"]}, {"WebAPI": ["Web API"]}, {"Web Services": ["WebServices"]}, {"Webdriver": ["Web Driver"]}, {"WebGL": []}, {"WebLogic": ["Web Logic"]}, {"WebRTC": ["Web RTC"]}, {"WebSockets": ["Web Sockets"]}, {"Websphere": ["Web Sphere"]}, {"Winforms": ["Winform", "Win Form", "Win Forms"]}, {"WPF": ["Windows Presentation Foundation", "Windows Presentation Foundations"]}, {"Xamarin": []}, {"XAML": []}, {"XCode": []}, {"XML": []}, {"xUnit": []}, {"Yii": ["Yii2"]}, {"Zend": []}, {"ZeroMQ": ["Zero MQ"]}]



synonymsDictionary = {'angularjs': 'angular', 'backbonejs': 'backbone', 'bootstrapjs': 'bootstrap', 'couchdb': 'couch',
		      'd3js': 'd3', 'dynamodb': 'dynamo', 'ef': 'entity framework', 'ef4': 'entity framework', 'ef5': 'entity framework', 'ef6': 'entity framework', 'elasticsearch': 'elastic', 'emberjs': 'ember', 'handlebar': 'handlebars', 'handlebarjs': 'handlebars', 'handlebarsjs': 'handlebars', 'hapijs': 'hapi', 'internet information services': 'iis', 'Java Server Faces': 'JSF', 'knockoutjs': 'knockout', 'koajs': 'koa',
		      'marionettejs': 'marionette', 'mongodb': 'mongo', 'ms mq': 'msmq', 'mssql': 'sql server', 'ms sql': 'sql server', 'my sql': 'mysql',
		      'nodejs': 'node', 'objective c': 'objective-c', 'open gl': 'opengl', 'postgresql': 'postgres',
		      'ravendb': 'raven', 'reactjs': 'react.js', 'restful': 'rest', 'svn': 'subversion', 'sails.js': 'sails', 'sailsjs': 'sails', 'sqlserver': 'sql server',
                      'tfs': 'team foundation server',
                      'transactsql': 't-sql', 'transact sql': 't-sql', 'transact-sql': 't-sql', 'tsql': 't-sql',
		      'underscorejs': 'underscore', 'web api': 'webapi', 'webservices': 'web services', 'winform': 'winforms' }
